In [ ]:
import numpy as np
rng = np.random.default_rng(43)
marks = rng.integers(0,101,size=(30,5))
print(marks)

[[ 51  65  40   4  58]
 [  2  27  84  46  59]
 [ 97  22  85  75  38]
 [ 26  27  42  64  45]
 [ 14  96  39  90  19]
 [ 28  78  28  90  42]
 [ 46   0  42  31  55]
 [ 96   1  84  40  54]
 [ 47  49  83  95  99]
 [ 59  70  95  94 100]
 [  4   3  58  11  87]
 [ 76  12  12  10  34]
 [ 85  30  71  55  60]
 [  5  68  45  14  56]
 [ 61  12  50  34  75]
 [ 50   3  30  56  42]
 [ 26  41  33   9  70]
 [ 59  53   7  67  58]
 [ 81   8  32  54  13]
 [ 85  24  29  39   8]
 [ 17  32  20  42  64]
 [ 61  87  15  64   0]
 [  0  85  37  45  88]
 [ 57  69  80  66  77]
 [ 12  87  41  32  16]
 [ 19  15   1  28  40]
 [ 95  61  76  57  80]
 [ 88  90  83  70  50]
 [ 17  12  94  50  81]
 [ 92   7  88  28  68]]


In [ ]:
np.shape(marks)

(30, 5)

In [ ]:
total = np.sum(marks,axis =1)
print(total)

[218 218 317 204 258 266 174 275 373 418 163 144 301 188 232 181 179 244
 188 185 175 227 255 349 188 103 369 381 254 283]


In [ ]:
average = np.mean(marks, axis = 1)
print(average)

[43.6 43.6 63.4 40.8 51.6 53.2 34.8 55.  74.6 83.6 32.6 28.8 60.2 37.6
 46.4 36.2 35.8 48.8 37.6 37.  35.  45.4 51.  69.8 37.6 20.6 73.8 76.2
 50.8 56.6]


In [ ]:
# Highest Student

top_student = np.argmax(total)
print(" TOP STUDENT NO :",top_student)
highest = np.max(total)
print("HIGHEST MARKS IS :",highest)

 TOP STUDENT NO : 9
HIGHEST MARKS IS : 418


In [ ]:
# Lowest Student
low_student = np.argmin(total)
print("LOWER STUDENT NO :",low_student)
lowest =np.min(total)
print("LOWEEST MARKS SI :", lowest)

LOWER STUDENT NO : 25
LOWEEST MARKS SI : 103


In [ ]:
# Pass/Fail
passed= average >= 40
print(passed)

[ True  True  True  True  True  True False  True  True  True False False
  True False  True False False  True False False False  True  True  True
 False False  True  True  True  True]


In [ ]:
# total passed
passed_student = np.sum(passed)
print(passed_student)

19


In [ ]:
# failed student
fail = average < 40
print(fail)

[False False False False False False  True False False False  True  True
 False  True False  True  True False  True  True  True False False False
  True  True False False False False]


In [ ]:
# number of the student who is failed the exam
failed_students = np.where(average < 40)

print(failed_students)

(array([ 6, 10, 11, 13, 15, 16, 18, 19, 20, 24, 25]),)


In [ ]:
# Grade System
grade = np.where(average >= 80, 'A',
                 np.where(average >= 70, 'B',
                          np.where(average >= 60, 'C',
                                   np.where(average>= 50, 'D','F'
                                            ))))
print(grade)

['F' 'F' 'C' 'F' 'D' 'D' 'F' 'D' 'B' 'A' 'F' 'F' 'C' 'F' 'F' 'F' 'F' 'F'
 'F' 'F' 'F' 'F' 'D' 'C' 'F' 'F' 'B' 'B' 'D' 'D']


In [ ]:
# average of the subject marks
subject_average = np.mean(marks, axis=0)

print(subject_average)

[48.53333333 41.13333333 50.8        48.66666667 54.53333333]
